---
- name: set vars
  set_fact:
    docker_image: '{{ role_speedtest-tracker_image }}'
    docker_container: '{{ role_speedtest-tracker_container }}'
    docker_puid: '{{ role_speedtest-tracker_puid }}'
    docker_pgid: '{{ role_speedtest-tracker_pgid }}'
    docker_tz: '{{ role_speedtest-tracker_tz }}'
    docker_dir_config: '{{ role_speedtest-tracker_dir }}/config'
    docker_network: '{{ role_speedtest-tracker_network }}'

- name: Create config directory
  ansible.builtin.file:
    path: '{{ docker_dir_config }}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Ensure image is pulled
  community.docker.docker_image:
    name: '{{ docker_image }}'
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: '{{ docker_container }}'
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: '{{ docker_container }}'
  register: result

- name: Create network
  community.docker.docker_network:
    name: '{{ docker_network }}'
    driver_options:
      com.docker.network.bridge.name: 'br-{{ docker_network }}'

- name: Create smokeping container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    volumes:
     - '{{ docker_dir_config }}:/config:Z'
     - '{{ docker_dir_data }}:/data:Z'
    env:
      PUID: '{{ docker_puid }}'
      PGID: '{{ docker_pgid }}'
      TZ: '{{ docker_tz }}'
      APP_KEY: '{{ role_speedtest-tracker_app_key }}'
      APP_URL: '{{ role_speedtest-tracker_app_url }}'
      DB_CONNECTION: 'sqlite'
      SPEEDTEST_SCHEDULE: '{{ role_speedtest-tracker_speedtest_schedule }}'
      SPEEDTEST_SERVERS: '{{ role_speedtest-tracker_speedtest_servers }}'
    name: '{{ docker_container }}'
    networks:
     - name: '{{ docker_network }}'
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
